# Server configuration
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 15s
  write_timeout: 15s
  shutdown_timeout: 30s

# Service connections
services:
  auth:
    host: "localhost"
    port: 50051
  wizard:
    host: "localhost"
    port: 50052
  mana:
    host: "localhost"
    port: 50053

# Security settings
security:
  jwt_secret: "your-secret-key-here"
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
    max_age: 300

# Rate limiting
rate_limit:
  requests_per_second: 10
  burst: 20

# Logging
logging:
  level: "info"
  format: "json"

# Metrics
metrics:
  enabled: true
  path: "/metrics"